### ISSUE TITLE
Key generation time is very long

### ISSUE THREAD

**Issue by yanzifan021** [google/private-join-and-compute#12]
Hi guys, i have been playing around the demo code for a while, and i realize that the key generation time varies a lot (from 15 s to 200s). Is it due to changing the default curve to NIST P-256?

**Comment by karnseth** [comment]
Hey Zifan,

The key generation time is 99% due to generating sufficiently large safe primes for the Paillier modulus. This is very resource intensive and in many cases longer than the actual protocol runtime. One fix is to generate the Paillier key offline and save and reuse them for each execution, but we don't include this in our current implementation.

**Comment by yanzifan021** [comment]
> Hey Zifan,
> 
> The key generation time is 99% due to generating sufficiently large safe primes for the Paillier modulus. This is very resource intensive and in many cases longer than the actual protocol runtime. One fix is to generate the Paillier key offline and save and reuse them for each execution, but we don't include this in our current implementation.

Thank you for the answer.
