### ISSUE TITLE
Why does the client sort the re-encrypted set ?

### ISSUE THREAD

**Issue by aarshkshah1992** [google/private-join-and-compute#2]
In client_lib.cc

```
td::sort(reencrypted_set.begin(), reencrypted_set.end(),
            [](const EncryptedElement& a, const EncryptedElement& b) {
              return a.element() < b.element();
            });
```

What would be happen if the client dosen't do this before sending this set to the server ?

**Comment by karnseth** [comment]
If the set wasn't sorted, the order of the re-encrypted items would be preserved, and the server may be able to learn which specific items were in the intersection (rather than only learning the intersection size or intersection sum)

The sorting serves as a way to shuffle the ordering before returning the values. Any other shuffle od the re-encrypted values that breaks the association with the original ordering would also work.
