### ISSUE TITLE
.pb.h header file not found

### ISSUE THREAD

**Issue by wangtsiao** [google/private-join-and-compute#31]
First of all, thank you for your work. I have successfully compiled and ran this program.

Now I am analyzing the code of this project, I found in `private_join_and_compute/util/elgamal_key_util.h` that header file "private_join_and_compute/crypto/elgamal.pb.h" not found. Can someone explain to me why

**Comment by wangtsiao** [comment]
In addition, for this project, are there any papers explaining the underlying principles?

**Comment by karnseth** [comment]
Hi @wangtsiao 
I'm able to build and run correctly with the following command:
bazel test --cxxopt='-std=c++17' //private_join_and_compute/util:elgamal_key_util_test

Could you try again after updating to the latest version of the code, and the most up-to-date bazel version as well? If it still doesn't work, could you share details of your OS?

If the code runs, I think your question may be about the actual file private_join_and_compute/crypto/elgamal.pb.h. This is actually a generated code file, which will be created after buildign the rule //:private_join_and_compute/crypto/elgamal_proto.

Once you've built this rule, you can look at the actual generated header file in bazel-out/k8-fastbuild/bin/private_join_and_compute/crypto/elgamal.pb.h (your exact path might differ slightly).

This file is generally pretty hard to read since it's generated code. You can look at a [guide](https://developers.google.com/protocol-buffers/docs/reference/cpp-generated) to get a better understanding of what the generated code has in it.

In terms of background, you can check out [the accompanying blog post](https://security.googleblog.com/2019/06/helping-organizations-do-more-without-collecting-more-data.html). It has pointers to the full paper, which itself references several academic works in the area.

**Comment by wangtsiao** [comment]
It turned out to be so, thank you for your patient answers and academic materials.
